/*
 * graphics.h
 *
 *  Created on: Jan 2, 2020
 *      Author: Karim
 */
#pragma once
#ifndef GRAPHICS_H_
#define GRAPHICS_H_

#include <nds.h>
/*
 * Structure encapsulating all the needed informations need to
 * draw the illustration (background or sprite) on the screen,
 * all of those are provided in the header file generated by
 * the grit(in the build folder)
 */
typedef struct{
	void * palette;
	void* tiles;
	void* map;     // null if sprite
	int palette_length;
	int tiles_length;
	int map_length;  // 0 if sprite
}Illustration;

/*!
 * @brief Sets the upper screen with a given background,
 * 		   it uses the VRAM_A and the Background 0 in Mode 0,
 * 		   (Tile mode). It saves the map in BG_MAP_RAM_SUB(0) and
 * 			the tiles in BG_TILE_RAM_SUB(1)
 * @param b the background to set
 */
void configure_background_main();

/*!
 * @brief Sets the upper screen with a given background,
 * 		   it uses the VRAM_C and the Background 0 in Mode 0,
 * 		   (Tile mode). It saves the map in BG_MAP_RAM(0) and
 * 			the tiles in BG_TILE_RAM(1)
 * @param b the background to set
 */
void configure_background_sub();

void draw_background_main(Illustration background);
void draw_background_sub(Illustration background);

/*
 *@brief Initializes the 2D sprite engine and enables the Vram B
 *
 */
void configure_sprites_main();

void configure_sprites_sub();
// global variable to keep track of the last sprite id number
static int sprite_id_main=0;
static int sprite_id_sub=0;

/*
 *@brief Allocates graphics memory for the supplied sprite attributes,
 *		 copy the sprite tiles and palette ( WARNING: a unique palette,
 *		 must be used between all the sprites( 2 ways to do this:
 *		 1- putting all the sprites in a single png file before generating
 *		 the corresponding pallette.  or
 *		 2- Setting an upper limit of the size of each palette when generating
 *		 them, to a sum of maximum total of 256.)
 *
 *@param The size of the Sprite 32*32 or 8*8 etc..
 *@param The sprite to be allocated
 *@param id to be assigned the id number of the allocated sprite
 *
 *@return *gfx, the address in vram of the allocated sprite (*gfx)
 */
void* allocate_sprite_main(SpriteSize s, Illustration sprite, int *id);
void* allocate_sprite_sub(SpriteSize s, Illustration sprite, int *id);
void deallocate_sprite_main(void* gfx);
void deallocate_sprite_sub(void* gfx);

/*
 *
 */
void set_sprite_main(const void* gfx, int id,int x, int y);
void set_sprite_sub(const void* gfx, int id,int x, int y);

void draw_sprite_main();
void draw_sprite_sub();

#endif /* GRAPHICS_H_ */
